/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique ID of the failed message
 */
export type Id = string;
/**
 * ID of the message from PubSub
 */
export type Messageid = string;
export type Version = number;
/**
 * Number of retry attempts made
 */
export type Retrycount = number;
/**
 * Current retry status
 */
export type Status = "pending" | "success" | "failed";
/**
 * When the dead letter was created
 */
export type Createdat = string;
/**
 * When it was last retried
 */
export type Lasttriedat = string | null;
/**
 * Project ID of the publisher
 */
export type Publisherprojectid = string | null;
/**
 * Endpoint URL for the subscription
 */
export type Endpoints = string[] | null;
/**
 * Error message if retry failed
 */
export type Errormessage = string | null;
/**
 * Original topic path for the message
 */
export type Originaltopicpath = string | null;

export interface DeadLetter {
  _id: Id;
  messageId: Messageid;
  _version?: Version;
  originalMessage: Originalmessage;
  retryCount?: Retrycount;
  status?: Status;
  createdAt?: Createdat;
  lastTriedAt?: Lasttriedat;
  publisherProjectId?: Publisherprojectid;
  endPoints?: Endpoints;
  errorMessage?: Errormessage;
  originalTopicPath?: Originaltopicpath;
}
/**
 * The original message payload that failed
 */
export interface Originalmessage {
  [k: string]: unknown;
}
