/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique ID of the failed message
 */
export type Id = string;
export type Version = number;
/**
 * Name of the topic the message was received from
 */
export type Topicname = string;
/**
 * subscription string of the service that failed
 */
export type Subscription = string;
/**
 * Number of retry attempts made
 */
export type Retrycount = number;
/**
 * Current retry status
 */
export type Status = "pending" | "success" | "failed";
/**
 * When the dead letter was created
 */
export type Createdat = string;
/**
 * When it was last retried
 */
export type Lasttriedat = string | null;
/**
 * Project ID of the publisher
 */
export type Publisherprojectid = string;

export interface DeadLetter {
  _id: Id;
  _version?: Version;
  originalMessage: Originalmessage;
  topicName?: Topicname;
  subscription: Subscription;
  retryCount?: Retrycount;
  status?: Status;
  createdAt?: Createdat;
  lastTriedAt?: Lasttriedat;
  publisherProjectId?: Publisherprojectid;
}
/**
 * The original message payload that failed
 */
export interface Originalmessage {
  [k: string]: unknown;
}
