/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * traceback for debugging
 */
export type Traceback = string | null;
/**
 * The service endpoint that produced the error
 */
export type Serviceendpoint = string | null;

export interface ServiceErrorMessage {
  traceback?: Traceback;
  serviceEndpoint?: Serviceendpoint;
}
