/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
/**
 * Name field
 */
export type Name = string;
/**
 * email field
 */
export type Email = string | null;
/**
 * Password field
 */
export type Password = string | null;
export type Createdat = string;
/**
 * Role id
 */
export type Id1 = string;
/**
 * Role value
 */
export type Value = boolean;
/**
 * Role description
 */
export type Description = string;
/**
 * List of collections transacted by role
 */
export type Collectionstransacted = string[] | null;
/**
 * Message to show when user is unauthorized to perform this role action
 */
export type Unauthorizedmessage = string | null;
export type UserRoles = Role[];
/**
 * User type
 */
export type Usertype = string | null;
export type Version = number;

export interface User {
  _id: Id;
  name: Name;
  email?: Email;
  password?: Password;
  createdAt: Createdat;
  roles: UserRoles;
  userType?: Usertype;
  _version?: Version;
}
export interface Role {
  _id: Id1;
  value: Value;
  description: Description;
  collectionsTransacted?: Collectionstransacted;
  unauthorizedMessage?: Unauthorizedmessage;
  [k: string]: unknown;
}
